/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package CodeChallenges.Challenge10;

import java.util.Scanner;

public class App {

    public static void main(String[] args) {
        Scanner scanner = new Scanner(System.in);
        Stack stack = new Stack();
        int input;

        for (int i = 0; i < 4; i++) {
            System.out.println("Welcome, please enter the value you want to push inside the stack");
            input = scanner.nextInt();
            stack.push(input);
        }
        System.out.println(stack.printAll());


    }
}


///////////////////////////////////////////////Stack\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
/* paste this in main method to test it

Stack stack = new Stack();
        int input;
        System.out.println("Welcome, please enter the value you want to push inside the stack");

        for (int i = 0; i < 4; i++) {
            System.out.println("Another one");
            input = scanner.nextInt();
            stack.push(input);
        }
        System.out.println(stack.printAll());
        System.out.println("The value was deleted is => " + stack.pop());
        System.out.println("The top value now => " + stack.peek());
        System.out.println(stack.printAll());v
 */



////////////////////////////////////////////////Queue\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\

/*
 paste this in main method to test it

       Queue queue = new Queue();
        int input;
        System.out.println("Welcome, please enter the value you want to push inside the queue");
        for (int i = 0; i < 4; i++) {
            System.out.println("Another one");
            input = scanner.nextInt();
            queue.enqueue(input);
        }
        System.out.println(queue.printAll());
        System.out.println("The value was deleted from the front of the queue => " + queue.dequeue());
        System.out.println("The front value now => " + queue.peek());
        System.out.println(queue.printAll());
 */